export const GET_ALLL_BOOK = "GET_ALL_BOOK";
export const GET_RESE_USERCURREN = "GET_RESE_USERCURREN";
export const GET_BOOKITEM_BY_ID = "GET_BOOKITEM_BY_ID";
export const GET_BOOKITEM_BY_USER = "GET_BOOKITEM_BY_USER";
export const UPDATE_STATUS_BOOKRESE = "UPDATE_STATUS_BOOKRESE";
export const GET_ALL_BOOKITEM = "GET_ALL_BOOKITEM";
export const DELETE_BOOKRESE_BY_ID = "DELETE_BOOKRESE_BY_ID";
export const SEARCH = "SEARCH";